# Generated by Django 4.1.1 on 2022-09-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noble_building_llc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='noble_building_llc/images/')),
            ],
        ),
    ]
